name: smoke

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  call-minimal:
    permissions:
      contents: read
    uses: ./.github/workflows/_minimal.yml
    with:
      msg: bisect
